name: Build & Deploy to Namecheap (FTP)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Show what's actually in the repo root
      - name: Inspect workspace
        run: |
          pwd
          ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Enable pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm -v
          node -v

      - name: Install deps
        run: pnpm install --no-frozen-lockfile

      - name: Build
        run: pnpm build

      # Confirm dist exists before deploy
      - name: Show dist
        run: |
          echo "---- dist contents ----"
          ls -la dist || echo "dist not found"

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR }}   # /public_html/
          local-dir: dist/
          protocol: ftps
          port: 21
          log-level: verbose
